services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: challengerbank-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ChallengeBank@123"
    ports:
      - "14333:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
